# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bWsK8qcvf5CI7twPnB_F7vwqjqfSXI8e
"""

import streamlit as st
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, Rectangle, Polygon, Arc

# Ustawienia strony Streamlit
st.set_page_config(page_title="Święty Mikołaj w Streamlit", layout="centered")

def narysuj_mikolaja():
    """Rysuje postać Świętego Mikołaja za pomocą matplotlib i zwraca figurę."""

    # Tworzenie figury i osi (jak w Matplotlib)
    fig, ax = plt.subplots(figsize=(6, 8))

    # Ustawienie osi
    ax.set_xlim(-5, 5)
    ax.set_ylim(-6, 6)
    ax.set_aspect('equal') # Kluczowe, aby kształty się nie zniekształcały
    ax.axis('off') # Usuń osie dla czystszego rysunku

    # Ustawienia kolorów
    RED = '#E53935'
    WHITE = '#F5F5F5'
    SKIN = '#F7C9A9'
    BLACK = '#212121'
    GOLD = '#FFD700'

    # --- 1. Ciało (Body) ---
    body = Rectangle((-2.5, -3.5), 5, 4, color=RED, zorder=1)
    ax.add_patch(body)

    collar = Rectangle((-3, -3.5), 6, 0.5, color=WHITE, zorder=2)
    ax.add_patch(collar)

    belt = Rectangle((-3, -2.5), 6, 0.8, color=BLACK, zorder=3)
    ax.add_patch(belt)

    buckle = Rectangle((-0.7, -2.3), 1.4, 0.4, color=GOLD, zorder=4)
    ax.add_patch(buckle)

    # --- 2. Głowa i Twarz (Head and Face) ---
    head = Circle((0, 0), 1.5, color=SKIN, zorder=5)
    ax.add_patch(head)

    eye_l = Circle((-0.5, 0.5), 0.1, color=BLACK, zorder=6)
    eye_r = Circle((0.5, 0.5), 0.1, color=BLACK, zorder=6)
    ax.add_patch(eye_l)
    ax.add_patch(eye_r)

    nose = Circle((0, 0.2), 0.2, color=RED, zorder=6)
    ax.add_patch(nose)

    # --- 3. Broda i Wąsy (Beard) ---
    beard_main = Polygon([(-2.5, -0.5), (2.5, -0.5), (0, -3.5)], color=WHITE, zorder=5)
    ax.add_patch(beard_main)

    mustache_l = Arc((-1, 0), 2, 2, theta1=200, theta2=340, color=WHITE, linewidth=4, zorder=6)
    mustache_r = Arc((1, 0), 2, 2, theta1=200, theta2=340, color=WHITE, linewidth=4, zorder=6)
    ax.add_patch(mustache_l)
    ax.add_patch(mustache_r)

    # --- 4. Czapka (Hat) ---
    hat_peak = Polygon([(-2.5, 0.8), (2.5, 0.8), (0, 5)], color=RED, zorder=5)
    ax.add_patch(hat_peak)

    hat_band = Rectangle((-3, 0.8), 6, 0.7, color=WHITE, zorder=5)
    ax.add_patch(hat_band)

    pompon = Circle((0, 5), 0.5, color=WHITE, zorder=6)
    ax.add_patch(pompon)

    # --- 5. Ręce i Rękawiczki (Arms and Gloves) ---
    glove_l = Circle((-3.5, -2), 0.5, color=RED, zorder=4)
    glove_r = Circle((3.5, -2), 0.5, color=RED, zorder=4)
    ax.add_patch(glove_l)
    ax.add_patch(glove_r)

    cuff_l = Circle((-3, -2), 0.6, color=WHITE, zorder=3)
    cuff_r = Circle((3, -2), 0.6, color=WHITE, zorder=3)
    ax.add_patch(cuff_l)
    ax.add_patch(cuff_r)

    # --- 6. Nogi i Buty (Legs and Boots) ---
    boot_l = Rectangle((-2.2, -5.5), 1.4, 2, color=BLACK, zorder=5)
    boot_r = Rectangle((0.8, -5.5), 1.4, 2, color=BLACK, zorder=5)
    ax.add_patch(boot_l)
    ax.add_patch(boot_r)

    pants_l = Rectangle((-2.2, -4.5), 1.4, 1, color=WHITE, zorder=4)
    pants_r = Rectangle((0.8, -4.5), 1.4, 1, color=WHITE, zorder=4)
    ax.add_patch(pants_l)
    ax.add_patch(pants_r)

    return fig

# --- Główna funkcja Streamlit ---
def main():
    st.title("🎅 Streamlit: Postać Świętego Mikołaja")
    st.write("Rysunek geometryczny wygenerowany za pomocą Matplotlib.")

    # Wywołanie funkcji rysującej Matplotlib i pobranie figury
    santa_fig = narysuj_mikolaja()

    # Użycie st.pyplot do wyświetlenia figury w aplikacji Streamlit
    st.pyplot(santa_fig)

    st.markdown("---")
    st.caption("Postać złożona jest z prymitywnych kształtów Matplotlib (Rectangle, Circle, Polygon).")

if __name__ == '__main__':
    main()